modLoader="javafml"
loaderVersion="[38,)"
license="GPLv3"
[[mods]]
modId="videoplayer"
version="2.2.0"
displayName="VideoPlayer"
authors="Goedix"
description='''
This mod allows the playback of videos in the user interface (GUI), you can play videos for all connected users or for a specific user.
'''
credits="Thanks J-RAP for the help with the API"
[[dependencies.videoplayer]]
    modId="watermedia"
    mandatory=true
    versionRange="[1.3.32,)"
    ordering="AFTER"
    side="CLIENT"