modLoader="javafml"
loaderVersion="[38,)"
license="GPLv3"
[[mods]]
modId="videoplayer"
version="1.0"
displayName="VideoPlayer"
authors="Goedix"
description='''
This mod allows the playback of videos in the user interface (GUI), you can play videos for all connected users or for a specific user.
'''
credits="J-RAP"
[[dependencies.videoplayer]]
    modId="watermedia"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"